; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;==== ESP32 Umgebung ==========
; Flash: 16MB QD, PSRAM: 2MB QD
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags =						; wichtig damit serial monitor geht!!!! https://www.esp32.com/viewtopic.php?t=32621
    -D USE_ESP32 ; Definiert ein Makro für ESP32-spezifischen Code
	-D ARDUINO_USB_MODE=1			; wichtig damit serial monitor geht!!!!
    -D ARDUINO_USB_CDC_ON_BOOT=1	; wichtig damit serial monitor geht!!!!
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

;USBSerial is used by devices with a full USB hardware device (S2 & S3 atm).
;It should not be used by devices with a hardware USB aka HWCDC (the -C and -H series).
;For those devices, enable "USB CDC on boot" and the "Integrated USB JTAG" output.
;This will assign the Serial object to use the HWCDC.
;This is equivalent to "-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1"
;The HWCDC takes some time to initialize, so if you have a device in a reboot loop, you will often not see anything in the serial monitor, not even the boot log.

;upload_port = COM5
upload_speed = 115200
upload_protocol = esptool
board_upload.wait_for_upload_port = true

;monitor_port = COM5
monitor_speed = 115200
monitor_dtr = 0	; It may be possible that the USB-CDC implementation only outputs data if DTR is asserted. You can add monitor_dtr = 1
monitor_rts = 0

;==== Bibliotheken ====
lib_deps = 
	Wire@2.0.0
	marcmerlin/Framebuffer GFX@1.1.0
	adafruit/Adafruit GFX Library@1.11.11
	adafruit/Adafruit BusIO@1.17.0
	adafruit/Adafruit SSD1306@2.5.13
	fastled/FastLED@3.5.0	; ACHTUNG: v. 3.9.10 führt zu Fehler: FastLED/src/third_party/yves/I2SClockLessLedDriveresp32s3/src/I2SClockLessLedDriveresp32s3.h:8:10: fatal error: esp_memory_utils.h: No such file or directory =>  fatal error: esp_memory_utils.h: No such file or directory
	marcmerlin/FastLED NeoMatrix@1.2.0
	fortyseveneffects/MIDI Library@5.0.2
	h2zero/NimBLE-Arduino@2.1.3
	Wifi@2.0.0

;==== Teensy 4 Umgebung ==========
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 9600
build_flags = 
    -D USE_TEENSY ; Definiert ein Makro für Teensy-spezifischen Code

lib_deps = 
	marcmerlin/Framebuffer GFX@1.1.0
	adafruit/Adafruit GFX Library@1.11.11
	adafruit/Adafruit BusIO@1.17.0
	adafruit/Adafruit SSD1306@2.5.13
	fastled/FastLED@3.5.0	; ACHTUNG: v. 3.9.10 führt zu Fehler: FastLED/src/third_party/yves/I2SClockLessLedDriveresp32s3/src/I2SClockLessLedDriveresp32s3.h:8:10: fatal error: esp_memory_utils.h: No such file or directory =>  fatal error: esp_memory_utils.h: No such file or directory
	marcmerlin/FastLED NeoMatrix@1.2.0
	fortyseveneffects/MIDI Library@5.0.2
