; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [platformio]
; src_dir = src, external
; include_dir = include, external
; lib_dir = lib
; build_flags = -Iexternal


;==== Teensy 4 Umgebung ==========
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 9600
build_flags = 
    -D USE_TEENSY ; Definiert ein Makro für Teensy-spezifischen Code
	;-D_USE_CMSIS=1 -falign-functions=32 ; behebt den fehler: pio\libdeps\teensy40\TeensyTimerTool\src/inplace_function.h:317:54: error: static assertion failed: inplace_function cannot be constructed from object with this (large) alignment 
	;-D HAS_MIDI_IN
	
;-D__USE_CMSIS=1:
;Dies sorgt dafür, dass das CMSIS (Cortex Microcontroller Software Interface Standard) aktiviert wird, was für den ARM Cortex-M Prozessor (wie im Teensy 4.0) wichtig ist. Dadurch wird die CMSIS-Bibliothek verwendet, die für den Zugriff auf die Hardwareschnittstellen und Timer von ARM-basierten Mikrocontrollern verantwortlich ist. Es könnte sein, dass die TeensyTimerTool-Bibliothek und andere Teensy-spezifische Bibliotheken auf CMSIS zugreifen, um Funktionen wie Timer oder Interrupts zu steuern.
;-falign-functions=32:
;Diese Option setzt die Ausrichtung von Funktionen auf 32 Byte. Bei Mikrocontrollern mit ARM-Architektur ist dies häufig erforderlich, um sicherzustellen, dass Funktionen korrekt ausgerichtet werden und keine Speicherzugriffsfehler auftreten. Es könnte sein, dass die inplace_function-Klasse oder andere Bibliotheken in deinem Code spezifische Ausrichtungsanforderungen haben, und das Setzen dieser Option hat die Speicherprobleme behoben.

lib_deps = 
	adafruit/Adafruit GFX Library@^1.10.12
	marcmerlin/FastLED NeoMatrix@^1.2
	fastled/FastLED@^3.5.0
	adafruit/Adafruit BusIO@^1.10.1
	fortyseveneffects/MIDI Library@^5.0.2
	adafruit/Adafruit SSD1306@^2.5.1


;==== ESP32 Umgebung ==========
; Flash: 16MB QD, PSRAM: 2MB QD
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags =						; wichtig damit serial monitor geht!!!! https://www.esp32.com/viewtopic.php?t=32621
    -D USE_ESP32 ; Definiert ein Makro für ESP32-spezifischen Code
	-D ARDUINO_USB_MODE=1			; wichtig damit serial monitor geht!!!!
    -D ARDUINO_USB_CDC_ON_BOOT=1	; wichtig damit serial monitor geht!!!!
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

;USBSerial is used by devices with a full USB hardware device (S2 & S3 atm).
;It should not be used by devices with a hardware USB aka HWCDC (the -C and -H series).
;For those devices, enable "USB CDC on boot" and the "Integrated USB JTAG" output.
;This will assign the Serial object to use the HWCDC.
;This is equivalent to "-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1"
;The HWCDC takes some time to initialize, so if you have a device in a reboot loop, you will often not see anything in the serial monitor, not even the boot log.

;upload_port = COM5
upload_speed = 115200
upload_protocol = esptool
board_upload.wait_for_upload_port = true

;monitor_port = COM5
monitor_speed = 115200
monitor_dtr = 0	; It may be possible that the USB-CDC implementation only outputs data if DTR is asserted. You can add monitor_dtr = 1
monitor_rts = 0

;==== Bibliotheken ====
lib_deps = 
	Wire
	marcmerlin/Framebuffer GFX@^1.1
	adafruit/Adafruit GFX Library@^1.10.12
	marcmerlin/FastLED NeoMatrix@^1.2
	fastled/FastLED@^3.5.0
	adafruit/Adafruit BusIO@^1.10.1
	fortyseveneffects/MIDI Library@^5.0.2
	adafruit/Adafruit SSD1306@^2.5.1
	h2zero/NimBLE-Arduino@^2.1.0
	;marcmerlin/LEDMatrix


