// AUTOMATISCH GENERIERT von tools/songgen.py - nicht von Hand ändern
#pragma once

#include <Arduino.h>

void setGeneratedMarkerLEDs(byte songID, byte partID);	// Marker der generierten Songs

void gen_DancingOnMyOwn();	// #8 Dancing On My Own
void gen_AllTheThingsSheSaid();	// #31 All The Things She Said
void gen_GirlsJustWannaHaveFun();	// #33 Girls just wanna have fun

// Part-Nummern (case) der generierten Songs - für handgeschriebenen Code, der in einen Song springt (Trailer)
#define GEN_DANCINGONMYOWN_PAUSE 0
#define GEN_DANCINGONMYOWN_BASS 5
#define GEN_DANCINGONMYOWN_VERSE_1 10
#define GEN_DANCINGONMYOWN_VERSE_1B 15
#define GEN_DANCINGONMYOWN_PRE_CHORUS 20
#define GEN_DANCINGONMYOWN_CHORUS_1 25
#define GEN_DANCINGONMYOWN_CHORUS_1B 30
#define GEN_DANCINGONMYOWN_HOOK_1 35
#define GEN_DANCINGONMYOWN_HOOK_1_TAIL 40
#define GEN_DANCINGONMYOWN_STOP 45
#define GEN_DANCINGONMYOWN_VERSE_2 50
#define GEN_DANCINGONMYOWN_CHORUS_2 55
#define GEN_DANCINGONMYOWN_CHORUS_2B 60
#define GEN_DANCINGONMYOWN_HOOK_2 65
#define GEN_DANCINGONMYOWN_INSTRUMENTAL 70
#define GEN_DANCINGONMYOWN_BRIDGE 75
#define GEN_DANCINGONMYOWN_CORNER 80
#define GEN_DANCINGONMYOWN_SNARE_ROLL 85
#define GEN_DANCINGONMYOWN_CHORUS_3 90
#define GEN_DANCINGONMYOWN_HOOK_3 95
#define GEN_DANCINGONMYOWN_CHORUS_4 100
#define GEN_DANCINGONMYOWN_CHORUS_4B 105
#define GEN_DANCINGONMYOWN_HOOK_4 110
#define GEN_DANCINGONMYOWN_HOOK_5 115
#define GEN_DANCINGONMYOWN_HOOK_5_TAIL 120
#define GEN_DANCINGONMYOWN_OUTRO 125
#define GEN_GIRLSJUSTWANNAHAVEFUN_PAUSE 0
#define GEN_GIRLSJUSTWANNAHAVEFUN_INTRO 5
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_1 10
#define GEN_GIRLSJUSTWANNAHAVEFUN_INSTRUMENTAL_BREAK 15
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_2 20
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT 25
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE 30
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_TAIL 35
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE 40
#define GEN_GIRLSJUSTWANNAHAVEFUN_SYNTH_SOLO 45
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_3 50
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT_2 55
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2 60
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2_TAIL 65
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE_2 70
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA 75
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_2 80
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_3 85
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4 90
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4_TAIL 95
