// AUTOMATISCH GENERIERT von tools/songgen.py - nicht von Hand ändern
#pragma once

#include <Arduino.h>

void setGeneratedMarkerLEDs(byte songID, byte partID);	// Marker der generierten Songs
bool isGeneratedSong(byte songID);	// exakte Timeline -> main.cpp gleicht die Verspätung der Part-Wechsel aus

void gen_DancingOnMyOwn();	// #8 Dancing On My Own
void gen_BillieJean();	// #28 Billie Jean
void gen_AllTheThingsSheSaid();	// #31 All The Things She Said
void gen_GirlsJustWannaHaveFun();	// #33 Girls just wanna have fun

// Part-Nummern (case) der generierten Songs - für handgeschriebenen Code, der in einen Song springt (Trailer)
#define GEN_DANCINGONMYOWN_PAUSE 0
#define GEN_DANCINGONMYOWN_BASS 5
#define GEN_DANCINGONMYOWN_VERSE_1 10
#define GEN_DANCINGONMYOWN_VERSE_1B 15
#define GEN_DANCINGONMYOWN_PRE_CHORUS 20
#define GEN_DANCINGONMYOWN_CHORUS_1 25
#define GEN_DANCINGONMYOWN_CHORUS_1B 30
#define GEN_DANCINGONMYOWN_HOOK_1 35
#define GEN_DANCINGONMYOWN_HOOK_1_TAIL 40
#define GEN_DANCINGONMYOWN_STOP 45
#define GEN_DANCINGONMYOWN_VERSE_2 50
#define GEN_DANCINGONMYOWN_CHORUS_2 55
#define GEN_DANCINGONMYOWN_CHORUS_2B 60
#define GEN_DANCINGONMYOWN_HOOK_2 65
#define GEN_DANCINGONMYOWN_INSTRUMENTAL 70
#define GEN_DANCINGONMYOWN_BRIDGE 75
#define GEN_DANCINGONMYOWN_CORNER 80
#define GEN_DANCINGONMYOWN_SNARE_ROLL 85
#define GEN_DANCINGONMYOWN_CHORUS_3 90
#define GEN_DANCINGONMYOWN_HOOK_3 95
#define GEN_DANCINGONMYOWN_CHORUS_4 100
#define GEN_DANCINGONMYOWN_CHORUS_4B 105
#define GEN_DANCINGONMYOWN_HOOK_4 110
#define GEN_DANCINGONMYOWN_HOOK_5 115
#define GEN_DANCINGONMYOWN_HOOK_5_TAIL 120
#define GEN_DANCINGONMYOWN_OUTRO 125
#define GEN_BILLIEJEAN_PAUSE 0
#define GEN_BILLIEJEAN_DRUMS_INTRO 5
#define GEN_BILLIEJEAN_BASS_INTRO 10
#define GEN_BILLIEJEAN_SYNTH_INTRO 15
#define GEN_BILLIEJEAN_VERSE_1 20
#define GEN_BILLIEJEAN_I_AM_THE_ONE 25
#define GEN_BILLIEJEAN_VERSE_2 30
#define GEN_BILLIEJEAN_I_AM_THE_ONE_2 35
#define GEN_BILLIEJEAN_PEOPLE_ALWYS_TOLD_ME 40
#define GEN_BILLIEJEAN_STROBE 45
#define GEN_BILLIEJEAN_CHORUS_1 50
#define GEN_BILLIEJEAN_I_AM_THE_ONE_3 55
#define GEN_BILLIEJEAN_CHORUS_WEITER 60
#define GEN_BILLIEJEAN_I_AM_THE_ONE_4 65
#define GEN_BILLIEJEAN_INSTRUMENTAL 70
#define GEN_BILLIEJEAN_VERSE_2_A 75
#define GEN_BILLIEJEAN_I_AM_THE_ONE_5 80
#define GEN_BILLIEJEAN_DO_THINK_TWICE 85
#define GEN_BILLIEJEAN_VERSE_2_B 90
#define GEN_BILLIEJEAN_I_MA_THE_ONE 95
#define GEN_BILLIEJEAN_BABY 100
#define GEN_BILLIEJEAN_PEOPLE_ALWAYS_TOLD_ME 105
#define GEN_BILLIEJEAN_HEYHEY 110
#define GEN_BILLIEJEAN_CHORUS_2A 115
#define GEN_BILLIEJEAN_I_AM_THE_ONE_6 120
#define GEN_BILLIEJEAN_CHORUS_2B 125
#define GEN_BILLIEJEAN_I_AM_THE_ONE_7 130
#define GEN_BILLIEJEAN_INSTRUMENTAL_2 135
#define GEN_BILLIEJEAN_SOLO_A 140
#define GEN_BILLIEJEAN_THE_ONE_HALFTIME 145
#define GEN_BILLIEJEAN_INSTRUMENTAL_3 150
#define GEN_BILLIEJEAN_STOP 155
#define GEN_BILLIEJEAN_CHORUS_3A 165
#define GEN_BILLIEJEAN_I_AM_THE_ONE_8 170
#define GEN_BILLIEJEAN_INTRUMENTAL 175
#define GEN_BILLIEJEAN_I_AM_THE_ONE_9 180
#define GEN_BILLIEJEAN_INTRUMENTAL_2 185
#define GEN_BILLIEJEAN_OUTRO 190
#define GEN_BILLIEJEAN_NOT_MY_LOVER 195
#define GEN_ALLTHETHINGSSHESAID_PAUSE 0
#define GEN_ALLTHETHINGSSHESAID_SYNTH_INTRO 5
#define GEN_ALLTHETHINGSSHESAID_SYNTH_INTRO_TAIL 10
#define GEN_ALLTHETHINGSSHESAID_INTRO_ALL_THET 15
#define GEN_ALLTHETHINGSSHESAID_INTRO_THIS_IS_NOT_ENOUGH 20
#define GEN_ALLTHETHINGSSHESAID_VERSE_1A 25
#define GEN_ALLTHETHINGSSHESAID_VERSE_1B 30
#define GEN_ALLTHETHINGSSHESAID_WIEDERHOLUNG_NOBODY_ELSE 35
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS 40
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1 45
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH 50
#define GEN_ALLTHETHINGSSHESAID_SYNTH_SOLO_A 55
#define GEN_ALLTHETHINGSSHESAID_SYNTH_SOLO_B 60
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_A 65
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_B 70
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_B_BUILD_UP 75
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_2 80
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_2 85
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_2 90
#define GEN_ALLTHETHINGSSHESAID_MOTHER_LOOKING_AT_ME 95
#define GEN_ALLTHETHINGSSHESAID_DADDY_LOOKING_AT_ME 100
#define GEN_ALLTHETHINGSSHESAID_BUILD_UP 105
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_3 110
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_3 115
#define GEN_ALLTHETHINGSSHESAID_STOP 120
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_WEITER 125
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_3 130
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_4 135
#define GEN_ALLTHETHINGSSHESAID_CHRORUS_2 140
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_4 145
#define GEN_ALLTHETHINGSSHESAID_FADE_OUT 150
#define GEN_GIRLSJUSTWANNAHAVEFUN_PAUSE 0
#define GEN_GIRLSJUSTWANNAHAVEFUN_INTRO 5
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_1 10
#define GEN_GIRLSJUSTWANNAHAVEFUN_INSTRUMENTAL_BREAK 15
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_2 20
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT 25
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE 30
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_TAIL 35
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE 40
#define GEN_GIRLSJUSTWANNAHAVEFUN_SYNTH_SOLO 45
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_3 50
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT_2 55
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2 60
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2_TAIL 65
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE_2 70
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA 75
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_2 80
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_3 85
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4 90
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4_TAIL 95
