// AUTOMATISCH GENERIERT von tools/songgen.py - nicht von Hand ändern
#pragma once

#include <Arduino.h>

void setGeneratedMarkerLEDs(byte songID, byte partID);	// Marker der generierten Songs
bool isGeneratedSong(byte songID);	// exakte Timeline -> main.cpp gleicht die Verspätung der Part-Wechsel aus

void gen_DancingOnMyOwn();	// #8 Dancing On My Own
void gen_ILoveIt();	// #9 I Love It
void gen_Abcdefu();	// #15 abcdefu
void gen_APT();	// #17 APT.
void gen_TellItToMyHeart();	// #21 Tell It To My Heart
void gen_FridayImInLove();	// #25 Friday I'm In Love
void gen_BeMine();	// #26 Be Mine
void gen_IWannaDanceWithSomebody();	// #27 I Wanna Dance With Somebody
void gen_BillieJean();	// #28 Billie Jean
void gen_AllTheThingsSheSaid();	// #31 All The Things She Said
void gen_GirlsJustWannaHaveFun();	// #33 Girls just wanna have fun
void gen_ILoveItIntro();	// #80 I Love It Intro
void gen_AllTheThingsSheSaidIntro();	// #82 All The Things She Said Intro

// Part-Nummern (case) der generierten Songs - für handgeschriebenen Code, der in einen Song springt (Trailer)
#define GEN_DANCINGONMYOWN_PAUSE 0
#define GEN_DANCINGONMYOWN_BASS 5
#define GEN_DANCINGONMYOWN_VERSE_1 10
#define GEN_DANCINGONMYOWN_VERSE_1B 15
#define GEN_DANCINGONMYOWN_PRE_CHORUS 20
#define GEN_DANCINGONMYOWN_CHORUS_1 25
#define GEN_DANCINGONMYOWN_CHORUS_1B 30
#define GEN_DANCINGONMYOWN_HOOK_1 35
#define GEN_DANCINGONMYOWN_HOOK_1_TAIL 40
#define GEN_DANCINGONMYOWN_STOP 45
#define GEN_DANCINGONMYOWN_VERSE_2 50
#define GEN_DANCINGONMYOWN_CHORUS_2 55
#define GEN_DANCINGONMYOWN_CHORUS_2B 60
#define GEN_DANCINGONMYOWN_HOOK_2 65
#define GEN_DANCINGONMYOWN_INSTRUMENTAL 70
#define GEN_DANCINGONMYOWN_BRIDGE 75
#define GEN_DANCINGONMYOWN_CORNER 80
#define GEN_DANCINGONMYOWN_SNARE_ROLL 85
#define GEN_DANCINGONMYOWN_CHORUS_3 90
#define GEN_DANCINGONMYOWN_HOOK_3 95
#define GEN_DANCINGONMYOWN_CHORUS_4 100
#define GEN_DANCINGONMYOWN_CHORUS_4B 105
#define GEN_DANCINGONMYOWN_HOOK_4 110
#define GEN_DANCINGONMYOWN_HOOK_5 115
#define GEN_DANCINGONMYOWN_HOOK_5_TAIL 120
#define GEN_DANCINGONMYOWN_OUTRO 125
#define GEN_ILOVEIT_PAUSE 0
#define GEN_ILOVEIT_SYNTH_INTRO 5
#define GEN_ILOVEIT_VERSE_1 10
#define GEN_ILOVEIT_CHORUS_1 15
#define GEN_ILOVEIT_VERSE_2 20
#define GEN_ILOVEIT_CHORUS_2 25
#define GEN_ILOVEIT_YOURE_ON_A_DIFFERENT_ROAD 30
#define GEN_ILOVEIT_I_LOVE_IT 35
#define GEN_ILOVEIT_VERSE_3 40
#define GEN_ILOVEIT_CHORUS_3 45
#define GEN_ILOVEIT_YOURE_ON_A_DIFFERENT_ROAD_2 50
#define GEN_ILOVEIT_STOP 55
#define GEN_ILOVEIT_CHORUS_4 60
#define GEN_ILOVEIT_CHORUS_5 65
#define GEN_ABCDEFU_PAUSE 0
#define GEN_ABCDEFU_INTRO 5
#define GEN_ABCDEFU_STROBE 10
#define GEN_ABCDEFU_VERSE_1A 15
#define GEN_ABCDEFU_VERSE_1B 20
#define GEN_ABCDEFU_I_WAS_INTO_YOU 25
#define GEN_ABCDEFU_CHORUS_1 30
#define GEN_ABCDEFU_NA_NA_NA_NA 35
#define GEN_ABCDEFU_VERSE_2 40
#define GEN_ABCDEFU_STOP 45
#define GEN_ABCDEFU_VERSE_2_WEITER 50
#define GEN_ABCDEFU_I_WAS_INTO_YOU_2 55
#define GEN_ABCDEFU_CHORUS_2 60
#define GEN_ABCDEFU_NA_NA_NA_NA_2 65
#define GEN_ABCDEFU_CHORUS_3 70
#define GEN_ABCDEFU_TRIOLEN 75
#define GEN_APT_PAUSE 0
#define GEN_APT_BASSDRUM_INTRO 5
#define GEN_APT_VERSE_1 10
#define GEN_APT_CHORUS_1 15
#define GEN_APT_STOP 20
#define GEN_APT_APT_APT_APT 25
#define GEN_APT_IST_WHATEVER 30
#define GEN_APT_VERSE_2 35
#define GEN_APT_CHORUS_2 40
#define GEN_APT_STOP_2 45
#define GEN_APT_APT_APT_APT_2 50
#define GEN_APT_HEY 55
#define GEN_APT_GET_YA_GET_YA 60
#define GEN_APT_HOLD_ON 65
#define GEN_APT_NUR_VOCALS 70
#define GEN_APT_STROBO 75
#define GEN_APT_CHORUS_5 80
#define GEN_APT_APT_APT_APT_3 85
#define GEN_TELLITTOMYHEART_PAUSE 0
#define GEN_TELLITTOMYHEART_INTRO_CHORUS 5
#define GEN_TELLITTOMYHEART_VERSE 10
#define GEN_TELLITTOMYHEART_BRIDGE 15
#define GEN_TELLITTOMYHEART_PAUSE_2 20
#define GEN_TELLITTOMYHEART_SNAREAUFTAKT 25
#define GEN_TELLITTOMYHEART_CHORUS_1 30
#define GEN_TELLITTOMYHEART_VERSE_2 35
#define GEN_TELLITTOMYHEART_BRIDGE_2 40
#define GEN_TELLITTOMYHEART_PAUSE_3 45
#define GEN_TELLITTOMYHEART_SNAREAUFTAKT_2 50
#define GEN_TELLITTOMYHEART_CHORUS_2 55
#define GEN_TELLITTOMYHEART_SOLO 60
#define GEN_TELLITTOMYHEART_LOVE_ON_THE_RUN 65
#define GEN_TELLITTOMYHEART_PAUSE_4 70
#define GEN_TELLITTOMYHEART_SNAREAUFTAKT_3 75
#define GEN_TELLITTOMYHEART_CHORUS_3 80
#define GEN_TELLITTOMYHEART_CHORUS_4 85
#define GEN_TELLITTOMYHEART_OUTRO_F 90
#define GEN_TELLITTOMYHEART_OUTRO_G 95
#define GEN_TELLITTOMYHEART_OUTRO_A 100
#define GEN_FRIDAYIMINLOVE_PAUSE 0
#define GEN_FRIDAYIMINLOVE_INTRO 5
#define GEN_FRIDAYIMINLOVE_INTRO_2 10
#define GEN_FRIDAYIMINLOVE_VERSE_1 15
#define GEN_FRIDAYIMINLOVE_VERSE_1B 20
#define GEN_FRIDAYIMINLOVE_SATURDAY_WENT 25
#define GEN_FRIDAYIMINLOVE_VERSE_2 30
#define GEN_FRIDAYIMINLOVE_SOLO 35
#define GEN_FRIDAYIMINLOVE_VERSE_3 40
#define GEN_FRIDAYIMINLOVE_SATURDAY_WENT_2 45
#define GEN_FRIDAYIMINLOVE_DRESSED_UP 50
#define GEN_FRIDAYIMINLOVE_DRESSED_UP_2 55
#define GEN_FRIDAYIMINLOVE_STROBO 60
#define GEN_FRIDAYIMINLOVE_VERSE_4A 65
#define GEN_FRIDAYIMINLOVE_VERSE_4B 70
#define GEN_FRIDAYIMINLOVE_OUTRO_CHORUS_1 75
#define GEN_FRIDAYIMINLOVE_OUTRO_CHORUS_2 80
#define GEN_FRIDAYIMINLOVE_GIT_FADE_OUT 85
#define GEN_BEMINE_PAUSE 0
#define GEN_BEMINE_INTRO 5
#define GEN_BEMINE_VERSE_1A 10
#define GEN_BEMINE_VERSE_1B 15
#define GEN_BEMINE_YOU_GOT_ME_SO_HIGH 20
#define GEN_BEMINE_SNAREROLL 25
#define GEN_BEMINE_CHORUS_1 30
#define GEN_BEMINE_UEBERGANG 35
#define GEN_BEMINE_VERSE_2 40
#define GEN_BEMINE_IM_GOING_CRAZY 45
#define GEN_BEMINE_YOU_GOT_ME_SO_HIGH_2 50
#define GEN_BEMINE_SNAREROLL_2 55
#define GEN_BEMINE_CHORUS_2 60
#define GEN_BEMINE_STROBE 65
#define GEN_BEMINE_CHORUS_3 70
#define GEN_IWANNADANCEWITHSOMEBODY_PAUSE 0
#define GEN_IWANNADANCEWITHSOMEBODY_STROBO 5
#define GEN_IWANNADANCEWITHSOMEBODY_INTRO 10
#define GEN_IWANNADANCEWITHSOMEBODY_STROBO_2 15
#define GEN_IWANNADANCEWITHSOMEBODY_VERSE_1 20
#define GEN_IWANNADANCEWITHSOMEBODY_IVE_DONE_ALRIGHT 25
#define GEN_IWANNADANCEWITHSOMEBODY_UEBERGANG_CHORUS 30
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_1 35
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME 40
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_1_WEITER 45
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME_2 50
#define GEN_IWANNADANCEWITHSOMEBODY_STEHENDER_CHORD 55
#define GEN_IWANNADANCEWITHSOMEBODY_UEBERGANG_VERSE 60
#define GEN_IWANNADANCEWITHSOMEBODY_VERSE_2 65
#define GEN_IWANNADANCEWITHSOMEBODY_IVE_DONE_ALRIGHT_2 70
#define GEN_IWANNADANCEWITHSOMEBODY_UEBERGANG_CHORUS_2 75
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_2 80
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME_3 85
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_2_WEITER 90
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME_4 95
#define GEN_IWANNADANCEWITHSOMEBODY_SAY_YOU_WANNA_DANCE 100
#define GEN_IWANNADANCEWITHSOMEBODY_UEBERGANG 105
#define GEN_IWANNADANCEWITHSOMEBODY_I_NEED_A_MAN 110
#define GEN_IWANNADANCEWITHSOMEBODY_UEBERGANG_CHORUS_3 115
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_3 120
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME_5 125
#define GEN_IWANNADANCEWITHSOMEBODY_CHORUS_3_WEITER 130
#define GEN_IWANNADANCEWITHSOMEBODY_W_SMBDY_WHO_LOVES_ME_6 135
#define GEN_IWANNADANCEWITHSOMEBODY_SAY_YOU_WANNA_DANCE_2 140
#define GEN_IWANNADANCEWITHSOMEBODY_STROBE 145
#define GEN_IWANNADANCEWITHSOMEBODY_SAY_YOU_WANNA_DANCE_3 150
#define GEN_IWANNADANCEWITHSOMEBODY_STROBE_2 155
#define GEN_IWANNADANCEWITHSOMEBODY_SAY_YOU_WANNA_DANCE_4 160
#define GEN_IWANNADANCEWITHSOMEBODY_STROBE_3 165
#define GEN_IWANNADANCEWITHSOMEBODY_W_SOME 170
#define GEN_IWANNADANCEWITHSOMEBODY_BDY_WHO_LOVES_ME 175
#define GEN_BILLIEJEAN_PAUSE 0
#define GEN_BILLIEJEAN_DRUMS_INTRO 5
#define GEN_BILLIEJEAN_BASS_INTRO 10
#define GEN_BILLIEJEAN_SYNTH_INTRO 15
#define GEN_BILLIEJEAN_VERSE_1 20
#define GEN_BILLIEJEAN_I_AM_THE_ONE 25
#define GEN_BILLIEJEAN_VERSE_2 30
#define GEN_BILLIEJEAN_I_AM_THE_ONE_2 35
#define GEN_BILLIEJEAN_PEOPLE_ALWYS_TOLD_ME 40
#define GEN_BILLIEJEAN_STROBE 45
#define GEN_BILLIEJEAN_CHORUS_1 50
#define GEN_BILLIEJEAN_I_AM_THE_ONE_3 55
#define GEN_BILLIEJEAN_CHORUS_WEITER 60
#define GEN_BILLIEJEAN_I_AM_THE_ONE_4 65
#define GEN_BILLIEJEAN_INSTRUMENTAL 70
#define GEN_BILLIEJEAN_VERSE_2_A 75
#define GEN_BILLIEJEAN_I_AM_THE_ONE_5 80
#define GEN_BILLIEJEAN_DO_THINK_TWICE 85
#define GEN_BILLIEJEAN_VERSE_2_B 90
#define GEN_BILLIEJEAN_I_MA_THE_ONE 95
#define GEN_BILLIEJEAN_BABY 100
#define GEN_BILLIEJEAN_PEOPLE_ALWAYS_TOLD_ME 105
#define GEN_BILLIEJEAN_HEYHEY 110
#define GEN_BILLIEJEAN_CHORUS_2A 115
#define GEN_BILLIEJEAN_I_AM_THE_ONE_6 120
#define GEN_BILLIEJEAN_CHORUS_2B 125
#define GEN_BILLIEJEAN_I_AM_THE_ONE_7 130
#define GEN_BILLIEJEAN_INSTRUMENTAL_2 135
#define GEN_BILLIEJEAN_SOLO_A 140
#define GEN_BILLIEJEAN_THE_ONE_HALFTIME 145
#define GEN_BILLIEJEAN_INSTRUMENTAL_3 150
#define GEN_BILLIEJEAN_STOP 155
#define GEN_BILLIEJEAN_CHORUS_3A 165
#define GEN_BILLIEJEAN_I_AM_THE_ONE_8 170
#define GEN_BILLIEJEAN_INTRUMENTAL 175
#define GEN_BILLIEJEAN_I_AM_THE_ONE_9 180
#define GEN_BILLIEJEAN_INTRUMENTAL_2 185
#define GEN_BILLIEJEAN_OUTRO 190
#define GEN_BILLIEJEAN_NOT_MY_LOVER 195
#define GEN_ALLTHETHINGSSHESAID_PAUSE 0
#define GEN_ALLTHETHINGSSHESAID_SYNTH_INTRO 5
#define GEN_ALLTHETHINGSSHESAID_SYNTH_INTRO_TAIL 10
#define GEN_ALLTHETHINGSSHESAID_INTRO_ALL_THET 15
#define GEN_ALLTHETHINGSSHESAID_INTRO_THIS_IS_NOT_ENOUGH 20
#define GEN_ALLTHETHINGSSHESAID_VERSE_1A 25
#define GEN_ALLTHETHINGSSHESAID_VERSE_1B 30
#define GEN_ALLTHETHINGSSHESAID_WIEDERHOLUNG_NOBODY_ELSE 35
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS 40
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1 45
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH 50
#define GEN_ALLTHETHINGSSHESAID_SYNTH_SOLO_A 55
#define GEN_ALLTHETHINGSSHESAID_SYNTH_SOLO_B 60
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_A 65
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_B 70
#define GEN_ALLTHETHINGSSHESAID_VERSE_2_B_BUILD_UP 75
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_2 80
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_2 85
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_2 90
#define GEN_ALLTHETHINGSSHESAID_MOTHER_LOOKING_AT_ME 95
#define GEN_ALLTHETHINGSSHESAID_DADDY_LOOKING_AT_ME 100
#define GEN_ALLTHETHINGSSHESAID_BUILD_UP 105
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_3 110
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_3 115
#define GEN_ALLTHETHINGSSHESAID_STOP 120
#define GEN_ALLTHETHINGSSHESAID_CHORUS_1_WEITER 125
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_3 130
#define GEN_ALLTHETHINGSSHESAID_UEBERGANG_ZUM_CHORUS_4 135
#define GEN_ALLTHETHINGSSHESAID_CHRORUS_2 140
#define GEN_ALLTHETHINGSSHESAID_THIS_IS_NOT_ENOUGH_4 145
#define GEN_ALLTHETHINGSSHESAID_FADE_OUT 150
#define GEN_GIRLSJUSTWANNAHAVEFUN_PAUSE 0
#define GEN_GIRLSJUSTWANNAHAVEFUN_INTRO 5
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_1 10
#define GEN_GIRLSJUSTWANNAHAVEFUN_INSTRUMENTAL_BREAK 15
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_2 20
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT 25
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE 30
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_TAIL 35
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE 40
#define GEN_GIRLSJUSTWANNAHAVEFUN_SYNTH_SOLO 45
#define GEN_GIRLSJUSTWANNAHAVEFUN_VERSE_3 50
#define GEN_GIRLSJUSTWANNAHAVEFUN_THATS_ALL_THEY_REALLY_WANT_2 55
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2 60
#define GEN_GIRLSJUSTWANNAHAVEFUN_WHEN_THE_WORKING_DAY_IS_DONE_2_TAIL 65
#define GEN_GIRLSJUSTWANNAHAVEFUN_FUN_GIRLS_THEY_WANNA_HAVE_2 70
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA 75
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_2 80
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_3 85
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4 90
#define GEN_GIRLSJUSTWANNAHAVEFUN_THEY_JUST_WANNA_4_TAIL 95
#define GEN_ILOVEITINTRO_PAUSE 0
#define GEN_ILOVEITINTRO_TEXT_NERDS_ON_FIRE 5
#define GEN_ILOVEITINTRO_PAUSE_2 10
#define GEN_ILOVEITINTRO_TEXT_SONGTITEL 15
#define GEN_ILOVEITINTRO_TEXT_SONGTITEL_TAIL 20
#define GEN_ILOVEITINTRO_STROBO 25
#define GEN_ALLTHETHINGSSHESAIDINTRO_PAUSE 0
#define GEN_ALLTHETHINGSSHESAIDINTRO_TEXT_NERDS_ON_FIRE 5
#define GEN_ALLTHETHINGSSHESAIDINTRO_TEXT_SONGTITEL 10
#define GEN_ALLTHETHINGSSHESAIDINTRO_TEXT_SONGTITEL_TAIL 15
#define GEN_ALLTHETHINGSSHESAIDINTRO_STROBO 20

// Einstieg eines Vorspanns in seinen Song (trailer_entry in show.yaml): die Matrix-Geräte zeigen dort erst den
// Titel-Lauftext (eigene Zusatz-cases), alle anderen Geräte beginnen direkt mit dem Part
#if defined(SCROLLMATRIX) || defined(GITBOARD)
#define GEN_ILOVEIT_TRAILER 16
#else
#define GEN_ILOVEIT_TRAILER 15
#endif
#if defined(SCROLLMATRIX) || defined(GITBOARD)
#define GEN_ALLTHETHINGSSHESAID_TRAILER 16
#else
#define GEN_ALLTHETHINGSSHESAID_TRAILER 15
#endif
